### PR TITLE
Fix -R and stdin, out, err

### PR DESCRIPTION
**Pull request by fakoua**
- Fix deno arg -R to -r
- Set stdin, out, err, to null to avoid leak.

### CODE REVIEW

**Comment by AnandChowdhary** [comment]
Thanks for opening this PR, @fakoua!

Curious about your thinking: I added `inherit` to show the logs of a process running, which is pretty useful. Do you think `null` is better for this use case?

**Comment by fakoua** [comment]
Thank you @AnandChowdhary , 
To be honest with you, since Deno is not quite stable yet, I'm not sure about inherit, but from my humble experience with Deno, inherit causes random leaks especially in test unit in  random manner with random OS, especially with CI and matrix.
So to be in the safe side, I use null, and set stdout to pipe for example if I need to read the output and so on.

**Comment by fakoua** [comment]
I will close and reject this pr, since null causes error when the module needs to write to output, sorry, will PR with the multiple registry.

**Comment by AnandChowdhary** [comment]
No worries, thanks for the contribution! Perhaps you can open another PR to fix the `-R` flag?

**Pull request closed without merging**
